default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.17
  hooks:
    - id: uv-lock